Initialized wandb tracking: odin_pop_300_gen_100_mut_020_problem_2.1_run001_20251013_103357
Added wandb logging callback to EA
Enhanced progress monitoring enabled
Progress monitoring enabled for 300 individuals, 100 generations
EA Progress Monitoring Started
==================================================
Starting evolution: 300 individuals, 100 generations
Using 28 parallel workers for fitness evaluation
Sequence constraint: UUAWUARWUAMAGSGCSNNUSNANWRUACNNMWAUAGNUAUNNAGUAUYAAAAGUNANRNURGUNNARSYUUUAURGAKAAYGNUUUGGRUNYUGUNGMCRNGGWNNRKAKWGAUCKMAYCAGAUCKRCGNAKGCURUNCSSSAUGYGRCACMUNCGNYRGCUUMUUAWGWARWKCAWURAGGUNACNUMRWGKMCNWRGWUWWUAAGAUCGCNAAAY
Structure constraint: ...................((((((((..((((((.((((((......((((((((..........))))))))..)))))).))))))))))))))........((((((([[[((......]]]..))...)))))))((((((.[[[.))))))....((((((((.....((((((((....))))))))......))))))))...]]].....
Initializing population...
Initialized population with 300 individuals
Gen   1/100 (  1.0%) | Best: 0.0000, Avg: 0.0000, Diversity: 0.2409 | Time: 0.2min, ETA: calculating...
Gen   2/100 (  2.0%) | Best: 0.0000, Avg: 0.0000, Diversity: 0.2397 | Time: 0.3min, ETA: 15.7min
Gen   3/100 (  3.0%) | Best: 0.0000, Avg: 0.0000, Diversity: 0.2384 | Time: 0.5min, ETA: 14.9min
Error folding sequence UUAAUAGUUACAGGGCCCGUGCAAUGUACAACAAUAGCUAUCGAGUAUUAAAAGUGAAGAUGGUCAAAGCUUUAUAGAGAAUGUUUUGGAUCUUGUCGCCGCGGAGGGUAUAGAUCUCAUCAGAUCUACGGAGGCUAUUCGGGAUGCGACACCUCCGUUGGCUUCUUAAGAAAAGCAAUGAGGUGACGUAGAGUACGUAGAUUAUAAGAUCGCCAAAC: Command '['sudo', 'docker', 'exec', 'ipknot_runner', 'ipknot', '/work/tmp_dm72va4.fa']' returned non-zero exit status 130.
Traceback (most recent call last):
  File "/home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py", line 734, in <module>
    main()
  File "/home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py", line 678, in main
    run_experiment(experiment, device=args.device, problems_to_run=problems_to_run, run_number=args.run, enable_wandb=enable_wandb)
  File "/home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py", line 579, in run_experiment
    result = run_single_problem(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py", line 411, in run_single_problem
    ea.run_evolution()
  File "/home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/progress_monitor.py", line 138, in enhanced_run_evolution
    original_run_evolution()
  File "/home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/rna_folding_ea.py", line 575, in run_evolution
    fitness_scores = self.evaluate_fitness(self.population)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/rna_folding_ea.py", line 247, in evaluate_fitness
    fitness_scores = list(executor.map(evaluate_single, sequences))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 451, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 355, in wait
    waiter.acquire()
KeyboardInterrupt
